# fly.toml app configuration file generated for app-cool-star-4247 on 2024-07-31T16:51:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-cool-star-4247'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
