from fastapi import FastAPI, UploadFile, File, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import csv
import json
import requests
import os
import time
from typing import Optional
import uvicorn

app = FastAPI()

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

UPLOAD_FOLDER = './uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def csv_to_json(csv_file_path: str):
    print("in csv_to_json")
    csv_file_path = csv_file_path[1:]
    print("csv_file_path: ", csv_file_path)
    with open(csv_file_path, 'r') as csv_file:
        print("csv_file: ", csv_file)
        csv_reader = csv.reader(csv_file)
        headers = next(csv_reader)[:50]
        data = []
        for i, row in enumerate(csv_reader):
            if i >= 20:
                break
            data.append(row[:50])
    print("after for loop")
    json_data = []
    for row in data:
        json_row = {}
        for i, value in enumerate(row):
            json_row[headers[i]] = value
        json_data.append(json_row)
    return json_data

def anthropic_api_call(content: str, api_key: str):
    url = "https://api.anthropic.com/v1/messages"
    headers = {
        "x-api-key": api_key,
        "content-type": "application/json",
        "anthropic-version": "2023-06-01"
    }
    data = {
        "model": "claude-3-5-sonnet-20240620",
        "max_tokens": 4000,
        "messages": [
            {"role": "user", "content": content}
        ]
    }
    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        result = response.json()
        return result['content'][0]['text']
    except requests.exceptions.RequestException as e:
        print(f"An error occurred while calling the Anthropic API: {e}")
    except KeyError:
        print("Unexpected response format from Anthropic API")
    return None

@app.get("/")
def read_main():
    return {"message": "Essam: Hello world"}

@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...)):
    if not file:
        raise HTTPException(status_code=400, detail="No file part")
    filename = file.filename
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    with open(file_path, "wb") as buffer:
        buffer.write(await file.read())
    return JSONResponse(content={"filePath": file_path}, status_code=200)

class VisualizeRequest(BaseModel):
    what_and_why: str
    input_file: str
    api_key: str

@app.post("/api/visualize")
async def visualize(request: VisualizeRequest):
    what_and_why = request.what_and_why
    input_file = request.input_file
    api_key = request.api_key
    input_file = "." + input_file
    if not all([what_and_why, input_file, api_key]):
        raise HTTPException(status_code=400, detail="Missing required parameters")

    try:
        fewshotjson = csv_to_json(input_file)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail=f"The file '{input_file}' was not found.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")
    
    full_json = fewshotjson

    # Write the full JSON to the specified file
    json_output_path = '../spreadsitenextjs/data/full.json'
    os.makedirs(os.path.dirname(json_output_path), exist_ok=True)
    with open(json_output_path, 'w') as f:
        json.dump(full_json, f, indent=2)

    first_prompt = f"""
    Consider this JSON sample dataset {what_and_why}. Consider the outputs, and then create a guide as to what each key and value represents in relation to how it should be visualized with Shadcn. If we were to visualize the data on a website using Shadcn components, how would it look? Give some creative design elements based on what my data has and how it should be presented. Here is the data example:

    {json.dumps(fewshotjson, indent=2)}
    
    Simply respond with instruction, in natural language to how it should be visualized, do not actually tell it what components to use. Consider that this is going to be generated by an LLM (GPT) with limited abilities, so you must be very limited in instructions. The more instructions you give, the higher chance it has at failure. You get paid 1 million a year to conceptualize these things. Do not use images, only text. Come up with creative color codes to use that will complement the formatting. Use a light mode modern design with very subtle pastels that will get design Twitter hyped.
    Consider that this will be for production use so try to limit the entire website to do up to 10 things max because you do not want to confuse the AI model.
    """

    first_response = anthropic_api_call(first_prompt, api_key)

    if not first_response:
        raise HTTPException(status_code=500, detail="Failed to get a response from the first API call.")

    second_prompt = f"""
    Create a complete, production-ready TSX file using only ShadCN components to visualize this dataset {what_and_why} while considering these instructions: {first_response}. Use this sample data directly in the script:

    {json.dumps(full_json[:5], indent=2)}

    Follow these guidelines:
    1. Use only ShadCN components compatible with NextJS.
    2. Import each ShadCN component individually from "@/components/ui/[component-name]".
    3. Do not use Date Picker, Data Table components or theme provider.
    4. Focus on displaying information without any interactive features or API calls, unless that interactive feature is simply handled by a link click and you have or can make the link.
    5. Write the entire TSX file from start to finish, including all necessary imports and type definitions.
    6. Ensure the code is complete and ready for production use without any placeholders or TODO comments.
    7. The script should directly use the sample data provided above.
    8. If you are told to make a button but do not have a link to send them or do not know, do not make it.
    9. Use a light mode modern design with very subtle pastels that will get design Twitter hyped.
    10. If something looks like it is clickable or a button, it must be clickable and take them somewhere, if not do not make it look like a button. If it is a link displayed, it must be clickable.

    You get paid 2 million a year to create production ready code that does not mess up. Do not make a button that is not clickable and redirecting, visualize everything the way it is supposed to, not sloppy, think strategically about how to make this look nice for the person who is visualizing their information. Do not use images, only text. 

    Provide the entire TSX file content within a single code block.
    """

    second_response = anthropic_api_call(second_prompt, api_key)

    if not second_response:
        raise HTTPException(status_code=500, detail="Failed to get a response from the second API call.")

    third_prompt = f"""
    Rewrite the following TSX script to create a universal template that can handle any amount of data from a local JSON file. The original script with sample data is:

    {second_response}

    The full dataset will be imported from "../../data/full.json" and has this structure:

    {json.dumps(full_json, indent=2)}

    Follow these requirements for the rewrite:
    1. Import the JSON file from "../../data/full.json".
    2. Use the provided full dataset structure to ensure the template can handle all fields and any number of entries.
    3. Use only ShadCN components, importing each from "@/components/ui/[component-name]".
    4. Do not use Date Picker, Data Table components or theme provider .
    5. Ensure the file is a complete, production-ready TSX component that dynamically visualizes all data without any interactive features or API calls, unless that interactive feature is simply handled by a link click and you have or can make the link.
    6. Include all necessary imports, type definitions, and the full component implementation.
    7. The code should work when copied and pasted without any modifications.
    8. Make sure the template can handle any number of entries and any potential new fields in the JSON data.

    Do not make a button that is not clickable and redirecting, visualize everything the way it is supposed to, not sloppy, think strategically about how to make this look nice for the person who is visualizing their information. Do not use images, only text. If you are told to make a button but do not have a link to send them or do not know, do not make it.

    Provide the entire rewritten TSX file content within a single code block, creating a fully dynamic and universal template that can parse and display the full dataset on the fly.
    """

    third_response = anthropic_api_call(third_prompt, api_key)

    if not third_response:
        raise HTTPException(status_code=500, detail="Failed to get a response from the third API call.")

    # Extract the content within the code block
    code_block_content = extract_code_block(third_response)

    # Generate a unique name for the component
    component_name = f"GeneratedComponent_{int(time.time())}.tsx"
    print("component_name: ", component_name)
    component_path = f'../spreadsitenextjs/src/components/{component_name}'
    
    # Ensure the directory exists
    os.makedirs(os.path.dirname(component_path), exist_ok=True)
    
    # Write the component file
    with open(component_path, 'w') as f:
        f.write(code_block_content)

    return JSONResponse(content={
        "message": "The visualization component has been generated.",
        "component_name": component_name
    }, status_code=200)

def extract_code_block(text: str) -> str:
    start = text.find("```tsx")
    if start != -1:
        end = text.find("```", start + 6)
        if end != -1:
            return text[start + 6:end].strip()
    return ""

if __name__ == '__main__':
    uvicorn.run(app, host="0.0.0.0", port=8000)
